### ISSUE TITLE
Examples using PlanDefinition instead of OperationDefinition

### ISSUE THREAD

**Issue by LionelCremer** [hl7-be/pss#39]
Here are some examples that require validation and refinement by @bdc-ehealth:

Radiology: [Radiology Example](https://confluence.smals.be/pages/viewpage.action?pageId=303397889)
Antimicrobial: [Antimicrobial Example](https://confluence.smals.be/pages/viewpage.action?pageId=307431355)

In both examples, I have replaced the Operation endpoints with PlanDefinition endpoints. 
I have included a sequential diagram to compare the two solutions, demonstrating that the payload and response remain the same in both approaches.

**Comment by bdc-ehealth** [comment]
@LionelCremer 

I think we are not allowed to redefine the input of the $apply operation: https://www.hl7.org/fhir/R4/plandefinition-operation-apply.html

Another thing is that I could not find was the .input and .output  in ActivityDefinition: https://hl7.org/fhir/R4/activitydefinition.html and I don't see anything that can quickly replace it. So I am not sure yet how the Plandefinition.$apply can produce the resources that are needed.

**Comment by LionelCremer** [comment]
1. You mean that you are not sure that we can request the $apply with a combination of a POST and a specific FHIR resource as payload?
2. I've updated the ActivityDefinition contents.
The output is replaced by "ActivityDefinition.kind" and "ActivityDefinition.profile" and the input is simply removed.

What are the purpose of the "PlanDefinition.action[].input" and "PlanDefinition.action[].output"?

**Comment by bdc-ehealth** [comment]
@LionelCremer ,

something else I came across: ActivityDefinitionType.kind cannot be of type #Questionnaire. Only a limited list of resources is allowed: https://hl7.org/fhir/R4/valueset-request-resource-types.html

In the meantime, I applied your other corrections: the result can be seen here: https://build.fhir.org/ig/hl7-be/pss/branches/issue-39

**Comment by LionelCremer** [comment]
@bdc-ehealth ,
The branch validates the structure of the resources, but it doesn't validate the transaction between the EPD and PSS server. Right?

**Comment by bdc-ehealth** [comment]
Yes, indeed, plus I had to put some lines from your example in comment to make it validate. There are certainly still some issues with this proposal.
